file = open('Sample_file.txt', 'r')
print("Reading the first ten characters in the file:")
print(file.read(10))
file.close()
file = open('Sample_file.txt', 'r')
print("Reading the first line:")
print(file.readline())
file.close()
file = open('Sample_file.txt', 'r')
print("Reading the first 4 lines of the file:")
print(file.readline())
print(file.readline())
print(file.readline())
print(file.readline())
file.close()
file = open('Sample_file.txt', 'r')
print("Looping through the contents of the file:")
for line in file:
    print(line)
file.close()