file = open('file.txt', 'r')
print("Reading the file: ")
print(file.read())
file.close()
file = open('file.txt', 'w')
file.write("My father name is Codingal.")
file.close()
file = open('file.txt', "a")
file.write("\n My mother is Pengy.")
file.close()
file = open('file.txt', 'r')
print("Reading the file again after adding more information: ")
print(file.read())
