file = open('file.txt', 'r')
print("Reading the file: ")
print(file.read())
file.close()
file = open('file.txt', 'w')
file.write("My mother's name is Zinat.")
file.close()
file = open('file.txt', "a")
file.write("\n My mother is 33 years old. She was born on 17/2/1991.")
file.close()
file = open('file.txt', 'r')
print("Reading the file again after adding more information: ")
print(file.read())