fruits=['Apple','Mango','Guava','Banana','Watermelon']
print(len(fruits))
print(fruits[2])
print(fruits[-4])
fruits.append('Strawberry')
print("Updated list is", fruits)
fruits.remove('Guava')
print("Updated list is", fruits)
fruits.pop(0)
print("Updated list is", fruits)
fruits.sort()
print("Updated list is", fruits)
fruits.reverse()
print("Updated list is", fruits)
print("Updated list is", fruits*2)
fruits.clear()
print(fruits)