file = open('filepart2.txt', 'r')
print("Reading file: ")
print(file.read())
file.close()
file = open('filepart2.txt', 'r')
print("\n")
print("Reading 44 charecters:")
print(file.read(44))
file.close()
file = open('filepart2.txt', 'a')
file.write("\n I was born on 7th August 2015.")
file.close()
file = open('filepart2.txt', 'r')
print("Reading file: ")
print(file.read())
file.close()