file = open('filepart2.txt', 'r')
print(file.readline())
file.close()
file = open('filepart2.txt', 'r')
print("\n Reading 3 lines")
print(file.readline())
print(file.readline())
print(file.readline())
file.close()
file = open('filepart2.txt', 'r')
print("\n Looping through the file: ")
for line in file:
    print(line)
file.close()