from tkinter import *
window = Tk()
window.title('Rock, Paper Scissors!')
window.geometry('500x500')
window.config(bg='light blue')
entry = Entry(window, width=20, bg='white', fg='black', font=('Arial', 10))
entry.pack()
button = Button(window, text=' type 1 for rock, 2 for scissors and 3 for paper and click on me', bg='white', fg='black', font=('Arial', 10))
button.pack()
label = Label(window, text='Rock Paper Scissors', bg='light blue', fg='black', font=('Arial', 10))
label.pack()
label2 = Label(window, text='You chose: ', bg='light blue', fg='black', font=('Arial',10))
label2.pack()
label3 = Label(window, text='Did you win, lose or draw against the computer?', bg='light blue', fg='black', font=('Arial',10))
label3.pack()
button2 = Button(window, text='Click on me to play again!', bg='white', fg='black', font=('Arial',10))
button2.pack()             
window.mainloop()