from tkinter import *
window = Tk()
window.title('Interface')
window.geometry("200x200")
greeting = Label(text="Hi User", fg = 'red', bg='white')
button =Button(text='Click me', fg = 'orange',bg='black')
entry = Entry(fg = 'yellow', bg = 'black', width = 100)
greeting.pack()
button.pack()
entry.pack()
frame = Frame(master=window, relief=RAISED, borderwidth=5)
frame.pack()
label = Label(master=frame, text='Frame', fg = 'purple', bg ='blue')
label.pack()
textbox = Text(bg = 'maroon', fg='pink', width = 20)
textbox.pack()
window.mainloop()